/****************************************************************************
 * File Name 		: KeyWord.java
 * Package			: com.dxc.zurich.enums
 * Author			: pmusunuru2
 * Creation Date	: Feb 16, 2021
 * Project			: Zurich Automation - UKLife
 * CopyRight		: DXC
 * Description		: 
 * ****************************************************************************
 * | Mod Date	| Mod Desc									| Mod Ticket Id   |
 * ****************************************************************************
 * |			|											|				  |
 * | 			|		*									|	*			  |
 * ***************************************************************************/
package com.abc.project.enums;

import java.util.Arrays;
import java.util.List;

import org.apache.commons.lang3.StringUtils;

/**
 * @author pmusunuru2
 * @since Feb 16, 2021 10:57:52 am
 */
public enum KeyWord {

	//Functionlibrary-Keyword Case Name("Controller-Keyword Name")
	OPENURL("OPENURL"),
	OPENURL_ENV("OPENURLENV"),
	LAUNCH_APP("LaunchApp"),
	INPUT("INPUT"),
	FORMAT_INPUT("FORMATINPUT"),
	INPUT_ENV("INPUT_ENV"),
	INPUT_ROBOT("INPUTRBT"),
	INPUT_CAPTURED_ROBOT("INPUTCAPTUREDRBT"),
	INPUTCLEAR("INPUTCLEAR"),
	PASTE("PASTE"),
	CLICK("CLICK"),
	CLICK_DOWNLOAD_FILE("CLICKDOWNLOADFILE"),
	FORMAT_CLICK("FORMATCLICK"),
	CLICKON_LATESTNUM("CLICKONLATESTNUM"),
	SELECT("SELECT"),
	SELECT_ENV("SELECT_ENV"),
	SELECT_NEGATIVE("SELECT_NEGATIVE"),
	SELECT_NEGATIVE_ENV("SELECT_NEGATIVE_ENV"),
	SELECT_SPL("SELECTSPL"),
	SELECT_BYINDEX("SELECTBYINDEX"),
	SELECT_BYINDEX_ENV("SELECTBYINDEX_ENV"),
	EXIST_SELECT("EXISTSELECT"),
	EXIST_SELECT_ENV("EXISTSELECT_ENV"),
	SELECT_LIFEASSURED("SELECTLIFEASSURED"),
	VERIFY_PAGETITLE("VERIFYPAGETITLE"),
	CLICK_PAGEDOWN("CLICKPAGEDOWN"),
	CLICK_PAGEUP("CLICKPAGEUP"),
	CLICKESC("CLICKESC"),
	CLICKTAB("CLICKTAB"),
	CLICKENTER("CLICKENTER"),
	CLICK_CONTROL("CLICKCTRL"),
	CONTROL_CLICK("CTRLCLICK"),
	UPLOAD_FILE("UPLOADFILE"),
	UPLOAD_FILE_LOCAL("UPLOADLOCALFILE"),
	INPUT_RANDOM_STRING("INPUTRNDSTRING"),
	INPUT_CLIENT_NAME("INPUTCLIENTNAME"),
	RADIO_BUTTON("RADIOBUTTON"),
	RADIO_BUTTON_SELECT("RADIOBUTTONSELECT"),
	DUAL_RADIO_BUTTON("DUALRADIOBUTTON"),
	DUAL_RADIO_BUTTON_PORTAL("DUALRADIOBUTTONPORTAL"),
	DUAL_RADIO_BUTTON_IPIPELINE("DUALRADIOBUTTONIPIPELINE"),
	CHECKBOX("CHECKBOX"),
	CLICKMAINTAIN("CLICKMAINTAIN"),
	CLOSEBROWSER("CLOSEBROWSER"),
	CLOSEWINDOW("CLOSEWINDOW"),
	CLOSEALLWINDOWS("CLOSEALLWINDOWS"),
	SWITCHTO_NEWWINDOW("SWITCHTONEWWINDOW"),
	SWITCHTO_PARENTWINDOW("SWITCHTOPARENTWINDOW"),
	DESC("DESC"),
	DEFAULTCONTENT("DEFAULTCONTENT"),
	GETALLLINKS("GETALLLINKS"),
	GETATTRIBUTE_VALUE("GETATTRIBUTEVALUE"),
	GETATTRIBUTE_ALT("GETATTRIBUTEALT"),
	CAPTURE_USERNAME("CAPTUREUSERNAME"),
	CAPTURE_LASTNAME("CAPTURELASTNAME"),
	CAPTURE_POLICY_NUMS("CAPTUREPOLICYNUMS"),
	CAPTURE_POLICYNUMS_SDP("CAPTUREPOLICYNUMSSDP"),
	CAPTURE_REF_NUMS("CAPTUREREFNUM"),
	CAPTURE_PRE_APP_REF_NUMS("CAPTUREPREAPPREFNUM"),
	CAPTURE_DECISIONS("CAPTUREDECISIONS"),
	CAPTURE_WEB_ELEMENT_TEXT("CAPTUREWEBELEMENTTEXT"),
	DATE_FORMAT_CAPTURED_DATA("DTFORMATCAPTUREDDATA"),
	BACK_OFFICE_CAPTURE_LIFE_ASSURED("BOCDCAPTURELIFEASSURED"),
	BACK_OFFICE_CAPTURE_DOB("BOCDCAPTUREDATEOFBIRTH"),
	BACK_OFFICE_CAPTURE_APPLICATION_NUMBER("BOCDCAPTUREAPPLICATIONNUMBER"),
	BACK_OFFICE_CAPTURE_GENDER("BOCDCAPTUREGENDER"),
	BACK_OFFICE_CAPTURE_SMOKER_STATUS("BOCDCAPTURESMOKERSTATUS"),
	BACK_OFFICE_CAPTURE_UW_CASENO("BOCDCAPTUREUWCASENO"),
	BACK_OFFICE_CAPTURE_UW_CASENO_INPUT("BOCDCAPTUREUWCASENOINPUT"),
	BACK_OFFICE_CAPTURE_CUSTO_REFNO("BOCAPTURECUSTREFNUM"),
	BACK_OFFICE_CAPTURE_CUSTO_REFNO2("BOCAPTURECUSTREFNUM2"),
	BACK_OFFICE_CAPTURE_CUSTO_CLAIM_APPNO("BOCAPTURECLAIMAPPLNUM"),
	BACK_OFFICE_CAPTURE_CLAIM_REFNO("BOCAPTURECLAIMREFERENCE"),
	BACK_OFFICE_CAPTURE_CLAIM_REFTEXT("BOCAPTURECLAIMREFERENCEGETTEXT"),
	BACK_OFFICE_CAPTURE_ADVISORYNO("CAPTUREAPPLICATIONREFERENCENO"),
	BACK_OFFICE_CAPTURE_PAY_REFNO("BOCAPTUREPAYERREFERENCE"),
	BACK_OFFICE_CAPTURE_CUST_ACCNO("BOCAPTURECUSTOMERACCOUNT"),
	EXPAND_QUOTE_SUMMARY("EXPANDQUOTESUMMARY"),
	SELECT_IDNTYPG_CHKBOXS("SELECTIDNTYPGCHKBOXS"),
	CLIENT_OCCUPATION("CLIENT_OCCUPATION"),
	CLIENT_SPL_OCCUPATION("CLIENT_SPL_OCCUPATION"),
	CLIENT_1_OCCUPATION("CLIENT_1_OCCUPATION"),
	CLIENT_1_SPL_OCCUPATION("CLIENT_1_SPL_OCCUPATION"),
	CLIENT_2_OCCUPATION("CLIENT_2_OCCUPATION"),
	CLIENT_1_PMOCCUPATION("CLIENT_1_PMOCCUPATION"),
	CLIENT_2_PMOCCUPATION("CLIENT_2_PMOCCUPATION"),
	GOBACK("GOBACK"),
	GOFORWARD("GOFORWARD"),
	ISDISPLAYED("ISDISPLAYED"),
	ISNOTDISPLAYED("ISNOTDISPLAYED"),
	WEBELEMENTISNOTDISPLAYED("WEBELEMENTISNOTDISPLAYED"),
	ISSELECTED("ISSELECTED"),
	ISDESELECTED("ISDESELECTED"),
	ISENABLED("ISENABLED"),
	KEYDOWN("KEYDOWN"),
	OPENNEWTAB("OPENNEWTAB"),
	REFRESH("REFRESH"),
	EXISTINPUT("EXISTINPUT"),
	EXISTINPUT_ENV("EXISTINPUT_ENV"),
	FORMAT_EXISTINPUT("FORMAT_EXISTINPUT"),
	LONGWAIT("LONGWAIT"), 
	SHORTWAIT("SHORTWAIT"),
	MEDIUM_WAIT("MEDIUMWAIT"),
	DYNAMICWAIT("DYNAMICWAIT"), 
	SYNC_WAIT("SYNCWAIT"),
	WAITUNTIL_PAGE_LOAD("WAITUNTILPGLOAD"),
	VERIFY_TEXT("VERIFYTEXT"),
	VERIFY_EXACT_TEXT("VERIFYEXACTTEXT"),
	VERIFY_UWTEXT("VERIFYUWTEXT"),
	VERIFY_DROPDOWN_TEXT("VERIFYDROPDOWNTEXT"),
	VERIFY_ALERT("VERIFYALERT"),
	VERIFY_ROBOT_POPUP("VERIFYRBTPOPUP"),
	VERIFY_CAPTURED_WEB_ELEMENT_TEXT("VERIFYCAPTUREDWEBELEMENTTEXT"),
	VERIFY_CAPTURED_BO_LIFE_ASSURED("VERIFYLIFEASSURED"),
	VERIFY_CAPTURED_BO_DOB("VERIFYDATEOFBIRTH"),
	VERIFY_CAPTURED_BO_APPLICATION_NUMBER("VERIFYAPPLICATIONNUMBER"),
	VERIFY_CAPTURED_BO_GENDER("VERIFYGENDER"),
	VERIFY_CAPTURED_BO_SMOKER_STATUS("VERIFYSMOKESTATUS"),
	VERIFY_CAPTURED_BO_UW_CASENO("VERIFYUWCASENO"),
	VERIFY_PDF_TEXT("VERIFYPDFTEXT"),
	VERIFY_PDF_TEXTBYAREA("VERIFYPDFTEXTBYAREA"),
	VERIFY_IS_ENABLED("VERIFY_IS_ENABLED"),
	VERIFY_TEXTFIELD_EMPTY("VERIFYTEXTFIELDEMPTY"),
	VERIFY_IS_DISABLED("VERIFY_IS_DISABLED"),
	VERIFY_COLUMN_OPTIONS("VERIFY_COLUMN_OPTIONS"),
	VERIFY_TABLE_RECORDS("VERIFY_TABLE_RECORDS"),
	UPDATE_EXCEL("UPDATE_EXCEL"),
	FOCUSNCLICK("FOCUSNCLICK"),
	SCROLL("SCROLL"),
	SCROLL_TO("SCROLLTO"),
	FOCUSNENTER("FOCUSNENTER"),
	EXISTFOCUSNENTER("EXISTFOCUSNENTER"),
	FOCUSNPRESSSPACE("FOCUSNPRESSSPACE"),
	MEMORABLE_WORDS("MWORDS"),
	SCROLL_TOP("SCROLL_TOP"),
	GET_TABLEHEADERS("GETTABLEHEADERS"),
	GET_TABLEDATA("GETTABLEDATA"),
	TABLE_LINKCLICK("TABLELINKCLICK"),
	TABLE_BUTTONCLICK("TABLEBUTTONCLICK"),
	VERIFY_PAGECLICK("VERIFY_PAGECLICK"),
	VERIFY_SORTING("VERIFY_SORTING"),
	VERIFY_NUMERIC_SORTING("VERIFY_NUMERIC_SORTING"),
	VERIFY_SORTING_COLUMN("VERIFY_SORTING_COLUMN"),
	VERIFY_ASCENDINGORDER_SORTING_DESIREDCOLUMNS("VERIFY_ASCENDINGORDER_SORTING_DESIREDCOLUMNS"),
	VERIFY_DESCENDING_ORDER_SORTING_DESIREDCOLUMNS("VERIFY_DESCENDING_ORDER_SORTING_DESIREDCOLUMNS"),
	VERIFY_TABLECOLUMN("VEIFYTABLECOLUMN"),
	VERIFY_TABLE("VERIFYTABLE"),
	VERIFY_TABLE_BYCOLUMNKEY("VERIFYTABLECOLUMNKEY"),
	VERIFY_TABLE_BYCOLUMNKEY_SEMICOLON("VERIFYTABLEBYCOLUMNKEYSEMICOLON"),
	FOCUSN_SCRIPT_CLICK("FOCUSNSCRIPTCLICK"),
	UNDER_WRITING("UNDER"),
	QUESTIONARE_COUNTRY_DELETE("QUESTIONARE_COUNTRY_DELETE"),
	QUESTIONARE_SNOW_STATUS_UPDATE("QUESTIONARE_SNOW_STATUS_UPDATE"),	
	FETCH_TEXT("GET_TEXT_ERRORNOTIFICATION_FIRSTRECORD"),
	ENTER_SELECTED_NUMBEROFRECORDS("ENTERSELECTEDNUMBEROFRECORDS"),
	EXISTCLICK("EXISTCLICK"),
	TOGGLE_CHECKBOX("TOGGLECHECKBOX"),
	FORMAT_EXISTCLICK("FORMATEXISTCLICK"),
	QUESTIONARE_SERVERIPADDRESS_UPDATE("QUESTIONARE_SERVERIPADDRESS_UPDATE"),
	QUESTIONARE_PHYSICALVIRTUAL_UPDATE("QUESTIONARE_PHYSICALVIRTUAL_UPDATE"),
	MOUSEOVER("MOUSEOVER"),
	MOUSE_RIGHT_CLICK("MOUSERIGHTCLICK"),
	READ_EMAIL_OPEN_LINK("READEMAILOPENLINK"),
	READ_EMAIL_OPEN_LINK_JOINTLIFE("READEMAILOPENLINK_JOINTLIFE"),
	VERIFY_EMAIL_MESSAGE("VALIDATEEMAILMESSAGE"),
	VERIFY_EMAIL_MESSAGE_JOINTLIFE("VALIDATEEMAILMESSAGE_JOINTLIFE"),
	DOWNLOAD_EMAIL_ATTACHMENT("DOWNLOADEMAILATTACHMENT"),
	GETQUOTENSUMMARY("GETQUOTENSUMMARY"),
	ACCEPTALERT("ACCEPTALERT"),
	INPUT_CAPTURED_DATA("INPUTCAPTUREDDATA"),
	INPUT_PREVIOUS_CAPTURED_DATA("INPUTPREVCAPTUREDATA"),
	BKOFF_APPLICATION_INPUT("BKOFFAPPLICATIONINPUT"),
	BKOFF_QUOTEREF_INPUT("BKOFFQUOTEREFINPUT"),
	BACK_OFFICE_INPUT_REFERENCENO("BOINPUTCUSTREFNUM"),
	BACK_OFFICE_INPUT_REFERENCENO2("BOINPUTCUSTREFNUM2"),
	BACK_OFFICE_INPUT_APPLICATIONNO("BOINPUTCLAIMAPPLNUM"),
	BACK_OFFICE_INPUT_REFERENCE("BOINPUTCLAIMREFERENCE"),
	BACK_OFFICE_INPUT_REFERENCETEXT("BOINPUTCLAIMREFERENCEGETTEXT"),
	BACK_OFFICE_INPUT_ADDREFERENCENO("BOINPUTADVISORYREFERENCENO"),
	BACK_OFFICE_INPUT_PAY_REFERENCENO("BOINPUTPAYERREFERENCE"),
	BACK_OFFICE_INPUT_CUST_ACCNO("BOINPUTCUSTOMERACCOUNT"),
	BKOFF_POLICYINPUT("BKOFFPOLICYINPUT"),
	BKOFF_POLICYINPUT2("BKOFFPOLICYINPUT2"),
	BKOFF_POLICYINPUT3("BKOFFPOLICYINPUT3"),
	BKOFF_POLICYINPUT4("BKOFFPOLICYINPUT4"),
	BKOFF_POLICYINPUT5("BKOFFPOLICYINPUT5"),
	BKOFF_POLICYINPUT6("BKOFFPOLICYINPUT6"),
	FIRM_CHECK("FIRMCHECK"),
	SELECT_FRAME("SELECTFRAME"),
	DESELECT_FRAME("DESELECTFRAME"),
	SDP_OCCUPTNINPUT("SDPOCCUPTNINPUT"),
	ZOOM_BY_PERCENTAGE("ZOOMPERCENTAGE"),
	TAKE_FULLWINDOW_SCREENSHOT("TAKEFULLWINDSCRSHOT"),
	COPY_FULLWINDOW_SCREENSHOT("COPYFULLWINDSCRSHOT"),
	VERIFYPDF_BARCODE("VERIFYPDFBARCODE"),
	DOWNLOAD_DDINSTRUCTION_PDF("DOWNLOADDDINSTRUCTIONPDF"),
	IDENTIFYDD_INSTRUCTION("IDENTIFYDDINSTRUCTION"),
	IDENTIFYDD_INSTRUCTION_NEGATIVE("IDENTIFYDDINSTRUCTION_NEGATIVE"),
	VERIFY_IDENTIFYDD_INSTRUCTION("VERIFYIDENTIFYDDINSTRUCTION"),
	EDITDD_INSTRUCTION("EDITDDINSTRUCTION"),
	FINALIZE_DOC_DD_INSTRUCTION("FINALIZEDOCDDINSTRUCTION"),
	CAPTURE_PUBLICATIONS_CUSTOMER_DATA("CAPTUREPUBLICATIONSCUSTOMERDATA"),
	CONVERT_DATE("DATECONVERT"),
	VERIFY_IMAGE_FILES("VERIFYIMAGES"),
	VERIFY_TEXT_FILES("VERIFYTEXTFILES"),
	VERIFY_PDF_FILES("VERIFYPDFFILES"),
	CAPTURE_DATABASE_SIZE("CAPTUREDBSIZE"),
	VERIFY_DATABASE_SIZE("VERIFYDBSIZE"),
	VERIFY_LESS_DATABASE_SIZE("VERIFYLESSDBSIZE"),
	VERIFY_CONATINS_DATABASE_SIZE("VERIFYCONTAINSDBSIZE"),
	EXECUTE_DATABASE_QUERY("EXECUTEDBQUERY"),
	EXTRACT_DATABASE_DATA("EXTRACTDBDATA"),
	SIKULI_CLICK_ACTION("SIKULICLICK"),
	SIKULI_CLICK_SPL_ACTION("SIKULISPLCLICK"),
	SIKULI_INPUT_ACTION("SIKULIINPUT"),
	SIKULI_INPUT_SPL_ACTION("SIKULISPLINPUT"),
	ALM_TESTSET_NAME("ALMTESTSETNAME"),
	ALM_TESTSET_PATH("ALMTESTSETPATH"),
	ALM_TESTSET_ID("ALMTESTSETID"),
	ALM_TESTCASE_STATUS("ALMTESTCASESTATUS"),
	UPDATE_SYSTEM_DATE("UPDATESYSTEMDATE"),
	CAPTURE_RUNTIME_DATA("CAPTURERUNTIMEDATA"),
	INPUT_RANDOM_ALPHAMUMERIC("INPUTRNDALPHANUMERIC"),
	INPUT_RANDOM_NUMBER("INPUTRNDNUMBER"),
	VERIFY_BACKGROUND_COLOR("VERIFYBACKGROUNDCOLOR"),
	VERIFY_TEXT_COLOR("VERIFYTEXTCOLOR"),
	VERIFY_TEXT_SIZE("VERIFYTEXTSIZE"),
	CAPTURE_DECISION_PREMIUM("CAPTUREDECISIONPREMIUM"),
	EXECUTE_JS_SCRIPT("Execute JS Script"),
	STORE_BROWSER_SESSION("StoreBrowserSession"),
	USE_PREVIOUS_SESSION("UsePreviousSession"),
	USE_API_SESSION("UseApiSession"),
	CAPTURE_URL("CaptureUrl"),
	OPEN_CAPTURED_URL("INPUTCAPTUREDURL"),
	VERIFY_EXCEL_COLUMNS("VERIFYEXCELCOLUMNS"),
	INVALID("INVALID-KEYWORK");


	private String strKeyWord;


	KeyWord(String strKeyWord) {
		this.setKeyWord(strKeyWord);
	}

	/**
	 * @return the strKeyWord
	 */
	public String getKeyWord() {
		return strKeyWord;
	}

	/**
	 * @param strKeyWord the strKeyWord to set
	 */
	public void setKeyWord(String strKeyWord) {
		this.strKeyWord = strKeyWord;
	}
	
	@Override
	public String toString() {
		return getKeyWord();
	}

	public static KeyWord getKeyWordByName(final String strKeyWord) {
		List<KeyWord> lstKeyWords = Arrays.asList(KeyWord.values());
		KeyWord aKeyWord = lstKeyWords.stream().filter(keyWork -> StringUtils.equalsIgnoreCase(keyWork.getKeyWord(), strKeyWord)).findFirst().orElse(KeyWord.INVALID);
		return aKeyWord;
	}
}
